language: php
php:
  - 5.6
  - 7.0
script:
  # Allow php script to be executed
  - chmod -R 755 *
  # Check that library is not displaying anything on its own
  - cd utils/
  - RES=$(php wakeOnLan.php 2>&1)
  - echo $RES
  - echo "Test lib displaying nothing:"
  - if [[ $RES == "" ]];
    then echo "Success";
    else echo "Failure"; return 1;
    fi
  # Check that test is trying to wake up a device
  - cd ..
  - cd examples/BasicWakeDeviceOnLan/
  - RES=$(php index.php 2>&1)
  - echo $RES
  - if [[ $RES == *"is waking up!"* ]];
    then echo "Success";
    else echo "Test failed"; return 1;
    fi
